### ISSUE TITLE
Export string etc. from iOS as json

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-apps#14]

**Comment by raae** [comment]
Could not export as json. Needs to be tranformed into usable format. 
Might be best to manually do it so one can get nested json for instance.

**Comment by kjellivar** [comment]
Lagt inn i angular service på et json-aktig format

**Comment by raae** [comment]
Kanskje vi skal kommentere ut alle strenge og så dekommentere etterhvert som de blir brukt? Ikke sikkert det er behov for alle i den nye appen?
